import { createTheme, colorsTuple } from "@mantine/core";

const theme = createTheme({
  fontFamily: "Poppins",
  colors: {
    background: [
      "#ffffff",
      "#ffffff",
      "#ffffff",
      "#ffffff",
      "#ffffff",
      "#ffffff",
      "#ffffff",
      "#1f1f1f",
      "#1f1f1f",
      "#1f1f1f",
    ],
    secondary: [
      "#ffffff",
      "#ffffff",
      "#ffffff",
      "#ffffff",
      "#ffffff",
      "#ffffff",
      "#ffffff",
      "#2e2e2e",
      "#2e2e2e",
      "#2e2e2e",
    ],
    selected: [
      "#f1f3f5",
      "#f1f3f5",
      "#f1f3f5",
      "#f1f3f5",
      "#f1f3f5",
      "#f1f3f5",
      "#f1f3f5",
      "#3a3a3a",
      "#3a3a3a",
      "#3a3a3a",
    ],
    dark: [
      "#c9c9c9",
      "#b8b8b8",
      "#828282",
      "#696969",
      "#424242",
      "#2e2e2e",
      "#2e2e2e",
      "#242424",
      "#1f1f1f",
      "#141414",
    ],
    accent: colorsTuple("#ffe22f"),
  },
  primaryColor: "dark",
});
export { theme };
