version: 2
updates:
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      nextjs:
        patterns:
          - "next"
          - "@next/*"
    ignore:
      - dependency-name: "@types/*"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"