services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mploy-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    develop:
      watch:
      - action: rebuild
        path: ./backend/src  # Watch the entire src directory
    volumes:
      - ./backend:/app
    ports:
      - "35729:35729"
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - mploy-network
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    networks:
      - mploy-network

networks:
  mploy-network:
    driver: bridge
