spring:
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    database: 0
    timeout: 60000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG

server:
  port: 8080